console.log("1. Importing ./env");
require('./env.ts');
console.log("2. Importing express");
require('express');
console.log("3. Importing path");
require('path');
console.log("4. Importing vite");
require('vite');
console.log("5. Importing @google/genai");
require('@google/genai');
console.log("6. Importing stripe");
require('stripe');
console.log("7. Importing firebase-admin");
require('firebase-admin');
console.log("All modules imported successfully!");
