#!/usr/bin/expect -f
set timeout 30
spawn ssh -o StrictHostKeyChecking=no master_awqbxuyqcq@134.209.28.27 "kill \$(ps aux | grep 'node functions/server.cjs' | grep -v grep | awk '{print \$2}') ; cd /home/1150801.cloudwaysapps.com/mksqztfeks/public_html && nohup node functions/server.cjs > server.log 2>&1 < /dev/null &"
expect {
    -nocase "password:" {
        send "rW9MJAfvXn4n\r"
        expect eof
    }
    eof
}
