#!/usr/bin/expect -f
set timeout -1
spawn rsync -avz -e "ssh -o StrictHostKeyChecking=no" update-noon-key.cjs master_awqbxuyqcq@134.209.28.27:/home/1150801.cloudwaysapps.com/mksqztfeks/public_html/
expect "password:"
send "rW9MJAfvXn4n\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no master_awqbxuyqcq@134.209.28.27 "cd /home/1150801.cloudwaysapps.com/mksqztfeks/public_html && node update-noon-key.cjs"
expect "password:"
send "rW9MJAfvXn4n\r"
expect eof
