import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    confirm_delivery: 'Confirm Delivery',
    delivery_summary: 'Delivery Summary',
    pickup: 'Pickup',
    dropoff: 'Drop-off',
    distance: 'Distance',
    select_vehicle: 'Select Vehicle',
    payment_method: 'Payment Method',
    add_payment: 'Add Payment Method',
    total_fare: 'Total Fare',
    est_time: 'Est. Time',
    confirm_pay: 'Confirm & Pay Order',
    fastest: 'Fastest',
    best_medium: 'Best for Medium Loads',
    heavy_duty: 'Heavy Duty',
    eta: 'ETA',
    apple_pay: 'Apple Pay',
    mastercard: 'Mastercard ending in 4492',
    delivery_details: 'Delivery Details',
    smart_scan: 'Smart Scan',
    snap_photo: 'Snap a photo of the item',
    package_type: 'Package Type',
    describe_manually: 'Describe Manually',
    dimensions: 'Dimensions',
    ai_suggested: 'AI Suggested Specs',
    logistics: 'Logistics',
    pickup_address: 'Pickup Address',
    dropoff_address: 'Drop-off Address',
    schedule: 'Schedule',
    asap: 'ASAP',
    pickup_window: 'Pickup Window',
    calculate_quote: 'Calculate Delivery Quote',
    what_moving: 'What are we moving today?',
    describe_items: "Describe your items and I'll handle the logistics categorization for you.",
    quick_actions: 'Quick Actions',
    active_shipment: 'Active Shipment',
    in_transit: 'In Transit',
    good_evening: 'Good Evening',
    see_all: 'See All',
    furniture: 'Furniture',
    electronics: 'Electronics',
    documents: 'Documents',
    custom_load: 'Custom Load',
    sofas_beds: 'Sofas, beds, tables',
    tv_pc: 'TVs, PC, appliances',
    legal_files: 'Legal & sensitive files',
    specialized: 'Specialized items',
    live_tracking: 'Live Tracking',
    est_arrival: 'Estimated arrival time',
    picked_up: 'Picked Up',
    driver_on_way: 'Marcus is on the way to the drop-off location. Please ensure someone is available to receive it.',
    order_confirmed: 'Order Confirmed!',
    driver_on_way_notify: 'Your driver is on the way. We\'ll notify you when they arrive.',
    min: 'min',
    splash_title: 'USend',
    splash_subtitle: 'Smart Delivery',
    splash_desc: 'The smartest way to move anything, anywhere. Fast, secure, and fully tracked.',
    get_started: 'Get Started',
    next_gen_logistics: 'USend Smart Logistics',
    onboarding_title_1: 'AI Powered Scanning',
    onboarding_desc_1: "Just snap a photo of your item and we'll figure out the right vehicle and price.",
    onboarding_title_2: 'Instant Quotes',
    onboarding_desc_2: 'Get transparent pricing instantly. No hidden fees, no surprises.',
    onboarding_title_3: 'Real-time Tracking',
    onboarding_desc_3: 'Watch your delivery every step of the way with live GPS tracking.',
    skip: 'Skip',
    next: 'Next',
    motorcycle: 'Motorcycle',
    cargo_van: 'Cargo Van',
    moving_truck: 'Moving Truck',
    order_delivered: 'Order Delivered',
    rate_driver: 'Rate your driver',
    how_was_delivery: 'How was your delivery?',
    tip_driver: 'Tip Driver',
    done: 'Done',
    order_summary: 'Order Summary',
    total_paid: 'Total Paid',
    my_orders: 'My Orders',
    personal_info: 'Personal Info',
    payment_methods: 'Payment Methods',
    notifications: 'Notifications',
    security: 'Security',
    settings: 'Settings',
    logout: 'Logout',
    weight: 'Weight',
    clear_details: 'Clear Details',
    today: 'Today',
    enter_pickup: 'Enter Pickup Address',
    enter_destination: 'Enter Destination',
    ai_powered: 'AI Powered',
    merchant_portal: 'Merchant Portal',
    dashboard: 'Dashboard',
    batch_orders: 'Batch Orders',
    tracking: 'Tracking',
    payments: 'Payments',
    exit_portal: 'Exit Portal',
    create_batch_orders: 'Create Batch Orders',
    add_multiple_orders: 'Add multiple orders to be dispatched via 3rd party delivery.',
    import_csv: 'Import CSV',
    order_details: 'Order Details',
    fixed_platform_fee: 'Fixed Platform Fee',
    customer_name: 'Customer Name',
    phone: 'Phone',
    delivery_address: 'Delivery Address',
    order_amount: 'Order Amount',
    payment_type: 'Payment Type',
    card_prepaid: 'Card (Prepaid)',
    cash_on_delivery: 'Cash on Delivery',
    add_another_order: 'Add Another Order',
    cancel: 'Cancel',
    cancelled: 'Cancelled',
    dispatch_orders: 'Dispatch Orders',
    order_tracking: 'Order Tracking',
    monitor_active_deliveries: 'Monitor your active deliveries in real-time.',
    search_orders: 'Search orders...',
    live_map_integration: 'Live Map Integration',
    active_orders: 'Active Orders',
    assigned_driver: 'Assigned Driver',
    current_status: 'Current Status',
    customer_info: 'Customer Information',
    order_items: 'Order Items',
    delivery_notes: 'Delivery Notes',
    required_field: 'Required field',
    dashboard_overview: 'Dashboard Overview',
    welcome_back: "Welcome back! Here's what's happening today.",
    total_orders: 'Total Orders',
    active_deliveries: 'Active Deliveries',
    total_revenue: 'Total Revenue',
    platform_fees: 'Platform Fees',
    recent_orders: 'Recent Orders',
    view_all: 'View All',
    order_id: 'Order ID',
    customer: 'Customer',
    status: 'Status',
    amount: 'Amount',
    time: 'Time',
    payments_overview: 'Payments Overview',
    track_earnings: 'Track your earnings and platform fees.',
    net_earnings: 'Net Earnings',
    pending_cash: 'Pending Cash',
    fees_paid: 'Fees Paid',
    withdraw_funds: 'Withdraw Funds',
    transaction_history: 'Transaction History',
    net_amount: 'Net Amount',
    delivered: 'Delivered',
    pending: 'Pending',
    completed: 'Completed',
    collected: 'Collected',
    pending_collection: 'Pending Collection',
    card: 'Card',
    cash: 'Cash',
    export_report: 'Export Report',
    withdraw_to_bank: 'Withdraw to Bank',
    transaction_id: 'Transaction ID',
    date: 'Date',
    type: 'Type',
    assigning: 'Assigning...',
    placeholder_name: 'e.g. John Doe',
    placeholder_address: 'e.g. 123 Main St, City',
    customers: 'Customers',
    manage_customers: 'Manage your client relationships and check their order history.',
    total_spend: 'Total Spend',
    last_order: 'Last Order',
    join_date: 'Join Date',
    customer_details: 'Customer Details',
    average_order: 'Avg. Order',
    total_orders_placed: 'Total Orders Placed',
    contact_customer: 'Contact Customer',
    driver_mode: 'Driver Mode',
    switch_to_driver: 'Switch to driver account',
    recent_activity: 'Recent Activity',
    points: 'Points',
    total_spent: 'Total Spent',
    individual_order: 'Individual Order',
    create_single_delivery: 'Create a single delivery order for a customer.',
    dispatch_order: 'Dispatch Order',
    all: 'All',
    total: 'Total',
    notes_placeholder: 'Gate code, apartment #, etc.',
    delivery_date: 'Delivery Date',
    inventory: 'Inventory',
    integrations: 'Integrations',
    wallet_billing: 'Wallet & Billing',
    digital_wallet: 'Digital Wallet',
    wallet_desc: 'Manage your digital wallet balance and view your transaction history.',
    add_funds: 'Add Funds',
    top_up_wallet: 'Top-up Wallet',
    available_balance: 'Available Balance',
    cod_pending: 'COD Pending',
    recent_transactions: 'Recent Transactions',
    add_product: 'Add Product',
    search_products: 'Search products by name or ID...',
    all_categories: 'All Categories',
    product: 'Product',
    sku: 'SKU',
    price: 'Price',
    stock: 'Stock',
    actions: 'Actions',
    total_products: 'Total Products',
    low_stock: 'Low Stock',
    out_of_stock: 'Out of Stock',
    download_awb: 'Download AWB',
    settings_desc: 'Manage your store profile, KYC documents, and bank details.',
    store_profile: 'Store Profile',
    kyc_documents: 'KYC Documents',
    bank_details: 'Bank Details',
    store_info: 'Store Information',
    store_name: 'Store Name',
    address: 'Business Address',
    save_changes: 'Save Changes',
    kyc_verified: 'Account Verified',
    kyc_verified_desc: 'Your Commercial License and Emirates ID have been successfully verified.',
    commercial_license: 'Commercial License',
    owner_id: 'Emirates ID (Owner)',
    bank_account_details: 'Bank Account Details',
    bank_name: 'Bank Name',
    account_name: 'Account Holder Name',
    iban: 'IBAN',
    swift_code: 'SWIFT Code',
    account_number: 'Account Number',
    update_bank: 'Update Bank Details',
    integrations_desc: 'Connect your online store directly to USend Logistics for automated order creation.',
    ecommerce_platforms: 'E-Commerce Platforms',
    api_credentials: 'API Credentials',
    live_api_key: 'Live API Key',
    test_api_key: 'Test API Key',
    inventory_desc: 'Manage your products, track stock levels, and receive alerts.',
    cost: 'Cost',
    describe_placeholder: 'Describe your item...',
    orders: 'Orders',
    export: 'Export',
    method: 'Method',
    home: 'Home',
    active_job: 'Active',
    earnings: 'Earnings',
    profile: 'Profile',
    close: 'Close',
    active: 'Active',
    hub_personal: 'User Hub',
    hub_personal_subtitle: 'Individual Shipments',
    hub_personal_desc: 'Send single packages, documents, or gifts anywhere in the world with real-time tracking.',
    hub_business: 'Merchant Hub',
    hub_business_subtitle: 'Enterprise Logistics',
    hub_business_desc: 'Scalable logistics solutions, batch ordering, and advanced tracking for your business.',
    hub_tag_individual: 'Individual',
    hub_tag_enterprise: 'Corporate',
    hub_get_started: 'Get Started',
    hub_user_mobile: 'Mobile Ecosystem',
    admin_dashboard: 'Admin Console',
    admin_overview: 'System Overview',
    total_merchants: 'Total Merchants',
    total_users: 'Total Users',
    system_health: 'System Health',
    ai_insights: 'AI Insights',
    active_drivers: 'Active Drivers',
    anomaly_detection: 'Anomaly Detection',
    smart_triage: 'AI Smart Triage',
    login: 'Login',
    admin_login: 'Admin Access',
    admin_system_name: 'MERSAL ADMIN',
    admin_master_data: 'Master Data',
    admin_super_admin: 'Super Admin',
    admin_level_access: 'Level 5 Access',
    admin_days_short_7: '7D',
    admin_days_short_30: '30D',
    admin_dismiss: 'Dismiss',
    admin_investigate: 'Investigate',
    admin_run_scan: 'Run Full Scan',
    admin_optimize_grid: 'Optimize Grid',
    admin_global_health: 'Global Health',
    admin_uptime_desc: '99.8% System uptime. All nodes operational in DXB and AD regions.',
    admin_smart_triage_desc: 'AI is currently re-routing 42 drivers to avoid detected traffic anomalies in real-time.',
    admin_investigate_anomaly: 'Investigate Anomaly',
    menu: 'Main Menu',
    portals: 'Portals',
    requests_freight: 'Requests & Freight',
    unified_stock_catalog: 'Unified Stock Catalog',
    csv_batch_dispatches: 'CSV Batch Dispatches',
    ledger_cod_settling: 'Platform Wallets & Ledger',
    merchant_directory: 'Merchant Directory',
    users_directory: 'Users Directory',
    apis_webhooks: 'APIs & Webhooks',
    uae_network_control: 'UAE Network Control',
    admin_dashboard_center: 'Admin Dashboard Center',
    query_records: 'Query records...',
    sign_out: 'Sign Out',
    new_order: 'New Order',
    recipient_info: 'Recipient Info',
    recipient_name: 'Recipient Name',
    manual_orders: 'Manual Orders',
    get_quotes: 'Get Quotes',
    freight_orders: 'Freight Orders',
    request_quote: 'Request A Quote',
    manage_stock: 'Manage Stock',
    your_inventory: 'Your Inventory',
    invoices_payment: 'Invoices & Payments',
    warehouse_orders: 'Warehouse Orders',
    ecommerce: 'Ecommerce',
    couriers: 'Couriers',
    analytics: 'Analytics',
    statements: 'Statements',
    cod_payments: 'COD Payments',
    tax_reports: 'Tax Reports',
    freight_invoices: 'Freight Invoices',
    previous_orders: 'Previous Orders',
    view_all_orders: 'View All Orders',
    recipient: 'Recipient',
    recipient_address: 'Recipient Address',
    couriers_directory: 'Couriers & Fleet Directory',
    couriers_desc: 'Track, monitor, and configure active drivers, vehicle types, and COD cash on hand.',
    active_fleet: 'Active Fleet',
    vehicle_type: 'Vehicle Type',
    cod_collected_cash: 'Collected COD Cash',
    settle_cash: 'Settle COD Cash',
    cash_settled_success: 'COD Cash settled successfully!',
    tracking_map: 'Live Courier Telemetry Map',
    all_vehicles: 'All Vehicles',
    courier_motorcycle: 'Motorcycle',
    van: 'Delivery Van',
    sedan: 'Sedan',
    busy: 'Busy / On Delivery',
    add_courier: 'Add Courier',
    total_completed_trips: 'Total Completed Trips',
    performance_rating: 'Performance Rating',
    availability_status: 'Availability Status',
    financial_reconciliation: 'Courier Financial Reconciliation',
    financial_reconciliation_desc: 'Compare estimated quotes vs. actual volumetric billing invoices from couriers to detect margin leaks.',
    tracking_awb: 'Tracking / AWB',
    courier: 'Courier',
    est_weight: 'Est. Weight',
    actual_weight: 'Actual Volumetric Weight',
    quoted_price: 'Quoted Price',
    billed_invoice: 'Billed Invoice',
    margin_leak: 'Margin Leak',
    all_carriers: 'All Carriers',
    exceptions: 'Exceptions',
    matched: 'Matched',
    smart_courier_options: 'Smart Courier Options',
    found_rates: 'Found Rates',
    select_book: 'Select & Book',
    convert_quote: 'Convert Quote to Order',
    standard_a4: 'Standard A4 (PDF)',
    thermal_printer: 'Thermal Printer (ZPL)',
    download_label: 'Download Label',
    view_pdf: 'View PDF Label',
    create_rma: 'Create Return Request (RMA)',
    auto_fix: 'Auto-Fix',
    webhook_updates: 'Webhook Tracking',
    smart_routing: 'Smart Routing',
    sandbox_dispatch: 'Sandbox Dispatch',
    return_processing_alert: 'Generating reverse-pickup RMA label with courier...\n\nCheck your email for the Return Waybill.',
    error_missing_location: 'Error: Please specify both a valid Pickup Location and a Dropoff Location to calculate distance and dispatch.',
    address_validation_alert: 'Google Maps Address Validation applied. Standardized postal codes injected.',
    financial_overview: 'Financial Overview',
    revenue_settlements: 'Revenue vs Settlements (Weekly)',
    revenue: 'Revenue',
    settlements: 'Settlements',
    uae_ops_map: 'UAE Operations Map',
    live_origin: 'Live origin of requests across Emirates',
    merchant_api: 'Merchant API',
    mobile_apps: 'Mobile Apps',
    b2b_integrations: 'B2B Integrations',
    manual_entry: 'Manual Entry',
    active_containers: 'Active Containers',
    heavy_pipelines: 'Heavy logistics pipelines active',
    total_payload_weight: 'Total Payload Weight',
    active_pallet_count: 'Active Pallet Count',
    standard_block_size: 'Standard block packing size',
    freight_turnovers: 'Freight Turnovers',
    gross_billings: 'Gross commercial billings',
    heavy_freight_center: 'Heavy Freight Operations Center',
    shipment_id: 'Shipment ID',
    booked_by: 'Booked By',
    delivery_path: 'Delivery Path',
    gross_quote: 'Gross Quote',
    transit_status: 'Transit Status',
    clearance_action: 'Clearance Action',
    active_phone: 'Active Phone Number',
    success_rate: 'Success Rate',
    smart_solutions_title: 'Smart Solutions for',
    smart_solutions_shipping: 'Shipping',
    smart_solutions_subtitle: 'USend offers shipping tools that simplify logistics for modern businesses',
    start_now_hero: 'Start Now',
    talk_to_sales: 'Talk to Sales',
    about_usend: 'About USend Gateway',
    about_usend_desc: 'Pioneering logistics ecosystem seamlessly connecting local carriers to merchants via unified intelligent routing.',
    success_rate_title: 'Success Rate In On-Time Product Delivery',
    about_us: 'About Us'
  },
  ar: {
    confirm_delivery: 'تأكيد التوصيل',
    delivery_summary: 'ملخص التوصيل',
    pickup: 'نقطة الاستلام',
    dropoff: 'نقطة التسليم',
    distance: 'المسافة',
    select_vehicle: 'اختر المركبة',
    payment_method: 'طريقة الدفع',
    add_payment: 'إضافة طريقة دفع',
    total_fare: 'إجمالي الأجرة',
    est_time: 'الوقت المتوقع',
    confirm_pay: 'تأكيد ودفع الطلب',
    fastest: 'الأسرع',
    best_medium: 'الأفضل للأحمال المتوسطة',
    heavy_duty: 'للأحمال الثقيلة',
    eta: 'الوصول',
    apple_pay: 'أبل باي',
    mastercard: 'ماستركارد تنتهي بـ 4492',
    delivery_details: 'تفاصيل التوصيل',
    smart_scan: 'المسح الذكي',
    snap_photo: 'التقط صورة للمادة',
    package_type: 'نوع الطرد',
    describe_manually: 'وصف يدوي',
    dimensions: 'الأبعاد',
    ai_suggested: 'المواصفات المقترحة بالذكاء الاصطناعي',
    logistics: 'الخدمات اللوجستية',
    pickup_address: 'عنوان الاستلام',
    dropoff_address: 'عنوان التسليم',
    schedule: 'الجدولة',
    asap: 'في أقرب وقت',
    pickup_window: 'نافذة الاستلام',
    calculate_quote: 'حساب تكلفة التوصيل',
    what_moving: 'ماذا سننقل اليوم؟',
    describe_items: 'صف أغراضك وسأقوم بتصنيفها لوجستياً لك.',
    quick_actions: 'إجراءات سريعة',
    active_shipment: 'الشحنة النشطة',
    in_transit: 'في الطريق',
    good_evening: 'مساء الخير',
    see_all: 'عرض الكل',
    furniture: 'أثاث',
    electronics: 'إلكترونيات',
    documents: 'مستندات',
    custom_load: 'حمل مخصص',
    sofas_beds: 'أرائك، أسرة، طاولات',
    tv_pc: 'تلفزيونات، حواسيب، أجهزة',
    legal_files: 'ملفات قانونية وحساسة',
    specialized: 'مواد متخصصة',
    live_tracking: 'تتبع مباشر',
    est_arrival: 'وقت الوصول المتوقع',
    picked_up: 'تم استلام الشحنة',
    driver_on_way: 'ماركوس في طريقه إلى موقع التسليم. يرجى التأكد من وجود شخص لاستلامه.',
    order_confirmed: 'تم تأكيد الطلب!',
    driver_on_way_notify: 'سائقك في الطريق. سنخطرك عند وصوله.',
    min: 'دقيقة',
    splash_title: 'USend',
    splash_subtitle: 'توصيل ذكي',
    splash_desc: 'الطريقة الأذكى لنقل أي شيء، في أي مكان. سريع، آمن، ومتبع بالكامل.',
    get_started: 'ابدأ الآن',
    next_gen_logistics: 'USend للخدمات اللوجستية الذكية',
    onboarding_title_1: 'المسح المدعوم بالذكاء الاصطناعي',
    onboarding_desc_1: 'فقط التقط صورة لغرضك وسنحدد المركبة والسعر المناسبين.',
    onboarding_title_2: 'أسعار فورية',
    onboarding_desc_2: 'احصل على أسعار شفافة فوراً. لا رسوم خفية، لا مفاجآت.',
    onboarding_title_3: 'تتبع في الوقت الحقيقي',
    onboarding_desc_3: 'شاهد توصيلك في كل خطوة مع تتبع نظام تحديد المواقع المباشر.',
    skip: 'تخطي',
    next: 'التالي',
    motorcycle: 'دراجة نارية',
    cargo_van: 'فان بضائع',
    moving_truck: 'شاحنة نقل',
    order_delivered: 'تم التوصيل',
    rate_driver: 'قيّم سائقك',
    how_was_delivery: 'كيف كان التوصيل؟',
    tip_driver: 'إكرامية السائق',
    done: 'تم',
    order_summary: 'ملخص الطلب',
    total_paid: 'الإجمالي المدفوع',
    my_orders: 'طلباتي',
    personal_info: 'المعلومات الشخصية',
    payment_methods: 'طرق الدفع',
    notifications: 'التنبيهات',
    security: 'الأمان',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    weight: 'الوزن',
    clear_details: 'مسح التفاصيل',
    today: 'اليوم',
    enter_pickup: 'أدخل عنوان الاستلام',
    enter_destination: 'أدخل الوجهة',
    ai_powered: 'مدعوم بالذكاء الاصطناعي',
    merchant_portal: 'بوابة التاجر',
    dashboard: 'لوحة القيادة',
    batch_orders: 'طلبات مجمعة',
    tracking: 'التتبع',
    payments: 'المدفوعات',
    exit_portal: 'الخروج من البوابة',
    create_batch_orders: 'إنشاء طلبات مجمعة',
    add_multiple_orders: 'إضافة طلبات متعددة لإرسالها عبر شركة توصيل خارجية.',
    import_csv: 'استيراد CSV',
    order_details: 'تفاصيل الطلب',
    fixed_platform_fee: 'رسوم المنصة الثابتة',
    customer_name: 'اسم العميل',
    phone: 'رقم الهاتف',
    delivery_address: 'عنوان التوصيل',
    order_amount: 'قيمة الطلب',
    payment_type: 'طريقة الدفع',
    card_prepaid: 'بطاقة (مسبق الدفع)',
    cash_on_delivery: 'الدفع عند الاستلام',
    add_another_order: 'إضافة طلب آخر',
    cancel: 'إلغاء',
    cancelled: 'ملغي',
    dispatch_orders: 'إرسال الطلبات',
    order_tracking: 'تتبع الطلبات',
    monitor_active_deliveries: 'راقب عمليات التوصيل النشطة في الوقت الفعلي.',
    search_orders: 'البحث في الطلبات...',
    live_map_integration: 'تكامل الخريطة المباشرة',
    active_orders: 'الطلبات النشطة',
    assigned_driver: 'السائق المعين',
    current_status: 'الحالة الحالية',
    customer_info: 'معلومات العميل',
    order_items: 'عناصر الطلب',
    delivery_notes: 'ملاحظات التوصيل',
    required_field: 'حقل مطلوب',
    dashboard_overview: 'لوحة التحكم الشاملة',
    welcome_back: 'أهلاً بك مجدداً! إليك ملخص نشاطك اليوم.',
    total_orders: 'إجمالي الطلبات',
    active_deliveries: 'شحنات نشطة',
    total_revenue: 'إجمالي المبيعات',
    platform_fees: 'رسوم المنصة',
    recent_orders: 'أحدث الطلبات',
    view_all: 'عرض الكل',
    order_id: 'رقم الطلب',
    customer: 'العميل',
    status: 'الحالة',
    amount: 'المبلغ',
    time: 'الوقت',
    payments_overview: 'قسم المدفوعات',
    track_earnings: 'تتبع أرباحك وعمولات المنصة بدقة.',
    net_earnings: 'صافي الأرباح',
    pending_cash: 'مبالغ معلقة',
    fees_paid: 'الرسوم المدفوعة',
    withdraw_funds: 'طلب سحب',
    transaction_history: 'سجل العمليات المالية',
    net_amount: 'الصافي',
    delivered: 'تم التسليم',
    pending: 'قيد المراجعة',
    completed: 'مكتمل',
    collected: 'تم التحصيل',
    pending_collection: 'في انتظار التحصيل',
    card: 'بطاقة',
    cash: 'نقدي',
    export_report: 'تصدير تقرير',
    withdraw_to_bank: 'سحب للبنك',
    transaction_id: 'رقم المعاملة',
    date: 'التاريخ',
    type: 'النوع',
    assigning: 'جاري التعيين...',
    placeholder_name: 'مثال: محمد علي',
    placeholder_address: 'مثال: حي الرياض، شارع الملك فهد',
    customers: 'العملاء',
    manage_customers: 'إدارة علاقات العملاء ومراجعة سجل طلباتهم.',
    total_spend: 'إجمالي الإنفاق',
    last_order: 'آخر طلب',
    join_date: 'تاريخ الانضمام',
    customer_details: 'تفاصيل العميل',
    average_order: 'متوسط الطلب',
    total_orders_placed: 'إجمالي الطلبات',
    contact_customer: 'التواصل مع العميل',
    driver_mode: 'وضع السائق',
    switch_to_driver: 'الانتقال إلى حساب السائق',
    recent_activity: 'النشاط الأخير',
    points: 'النقاط',
    total_spent: 'إجمالي الإنفاق',
    individual_order: 'طلب فردي',
    create_single_delivery: 'إنشاء طلب توصيل فردي لعميل.',
    dispatch_order: 'إرسال الطلب',
    all: 'الكل',
    total: 'الإجمالي',
    notes_placeholder: 'رمز البوابة، رقم الشقة، إلخ.',
    delivery_date: 'تاريخ التوصيل',
    inventory: 'المخزون',
    integrations: 'الربط الإلكتروني',
    wallet_billing: 'المحفظة والفواتير',
    digital_wallet: 'المحفظة الرقمية',
    wallet_desc: 'إدارة رصيد محفظتك الرقمية وعرض سجل المعاملات.',
    add_funds: 'إضافة أموال',
    top_up_wallet: 'شحن المحفظة',
    available_balance: 'الرصيد المتاح',
    cod_pending: 'الدفع عند الاستلام معلق',
    recent_transactions: 'أحدث المعاملات',
    add_product: 'إضافة منتج',
    search_products: 'ابحث عن المنتجات بالاسم أو المعرف...',
    all_categories: 'كل الفئات',
    product: 'المنتج',
    sku: 'رمز المنتج',
    price: 'السعر',
    stock: 'المخزون',
    actions: 'إجراءات',
    total_products: 'إجمالي المنتجات',
    low_stock: 'مخزون منخفض',
    out_of_stock: 'نفذ من المخزون',
    download_awb: 'تحميل بوليصة الشحن (AWB)',
    settings_desc: 'إدارة ملف المتجر، وثائق اعرف عميلك (KYC)، والتفاصيل المصرفية.',
    store_profile: 'ملف المتجر',
    kyc_documents: 'وثائق اعرف عميلك (KYC)',
    bank_details: 'التفاصيل المصرفية',
    store_info: 'معلومات المتجر',
    store_name: 'اسم المتجر',
    address: 'عنوان العمل',
    save_changes: 'حفظ التغييرات',
    kyc_verified: 'تم التحقق من الحساب',
    kyc_verified_desc: 'تم التحقق من الرخصة التجارية أو الهوية الإماراتية الخاصة بك بنجاح.',
    commercial_license: 'الرخصة التجارية',
    owner_id: 'الهوية الإماراتية (المالك)',
    bank_account_details: 'تفاصيل الحساب المصرفي',
    bank_name: 'اسم البنك',
    account_name: 'اسم صاحب الحساب',
    iban: 'الآيبان (IBAN)',
    swift_code: 'رمز سويفت (SWIFT)',
    account_number: 'رقم الحساب',
    update_bank: 'تحديث التفاصيل المصرفية',
    integrations_desc: 'قم بربط متجرك الإلكتروني مباشرة مع لوجستيات USend لإنشاء الطلبات تلقائياً.',
    ecommerce_platforms: 'منصات التجارة الإلكترونية',
    api_credentials: 'بيانات اعتماد API',
    live_api_key: 'مفتاح API المباشر',
    test_api_key: 'مفتاح API التجريبي',
    inventory_desc: 'أدر منتجاتك، وتتبع مستويات المخزون، وتلقَّ التنبيهات.',
    cost: 'التكلفة',
    describe_placeholder: 'صف الغرض الخاص بك...',
    orders: 'طلبات',
    export: 'تصدير',
    method: 'الطريقة',
    home: 'الرئيسية',
    active_job: 'نشط',
    earnings: 'الأرباح',
    profile: 'الملف الشخصي',
    close: 'إغلاق',
    active: 'نشط',
    hub_personal: 'مركز المستخدم',
    hub_personal_subtitle: 'شحنات فردية',
    hub_personal_desc: 'أرسل طروداً مفردة، مستندات، أو هدايا لأي مكان في العالم مع تتبع فوري.',
    hub_business: 'مركز التاجر',
    hub_business_subtitle: 'لوجستيات الشركات',
    hub_business_desc: 'حلول لوجستية قابلة للتوسع، طلبات دفعات، وتتبع متقدم لعملك.',
    hub_tag_individual: 'أفراد',
    hub_tag_enterprise: 'شركات',
    hub_get_started: 'ابدأ الآن',
    hub_user_mobile: 'النظام البيئي للهاتف',
    admin_dashboard: 'لوحة التحكم للمسؤول',
    admin_overview: 'نظرة عامة على النظام',
    total_merchants: 'إجمالي التجار',
    total_users: 'إجمالي المستخدمين',
    system_health: 'سلامة النظام',
    ai_insights: 'رؤى الذكاء الاصطناعي',
    active_drivers: 'السائقين النشطين',
    anomaly_detection: 'كشف الانحرافات',
    smart_triage: 'التصنيف الذكي',
    login: 'تسجيل الدخول',
    admin_login: 'دخول المسؤول',
    admin_system_name: 'مسؤول USend',
    admin_master_data: 'البيانات الرئيسية',
    admin_super_admin: 'المسؤول الأعلى',
    admin_level_access: 'صلاحية المستوى 5',
    admin_days_short_7: '7 أيام',
    admin_days_short_30: '30 يوماً',
    admin_dismiss: 'تجاهل',
    admin_investigate: 'تحقيق',
    admin_run_scan: 'تشغيل فحص كامل',
    admin_optimize_grid: 'تحسين الشبكة',
    admin_global_health: 'الصحة العامة للنظام',
    admin_uptime_desc: '99.8٪ وقت تشغيل النظام. جميع النقاط تعمل في مناطق دبي وأبو ظبي.',
    admin_smart_triage_desc: 'يقوم الذكاء الاصطناعي حالياً بإعادة توجيه 42 سائقاً لتجنب الازدحامات المرورية المكتشفة في الوقت المباشر.',
    admin_investigate_anomaly: 'التحقيق في الانحراف',
    menu: 'القائمة الرئيسية',
    portals: 'البوابات',
    requests_freight: 'الطلبات والشحن',
    unified_stock_catalog: 'كتالوج المخزون الموحد',
    csv_batch_dispatches: 'شحنات دفعات CSV',
    ledger_cod_settling: 'المحافظ الإلكترونية و دفتر الحسابات',
    merchant_directory: 'دليل التجار',
    users_directory: 'دليل المستخدمين',
    apis_webhooks: 'مفاتيح ربط API والويب هوك',
    uae_network_control: 'تحكم شبكة الإمارات',
    admin_dashboard_center: 'مركز لوحة تحكم المسؤول',
    query_records: 'استعلام السجلات...',
    sign_out: 'تسجيل الخروج',
    new_order: 'طلب توصيل جديد',
    recipient_info: 'معلومات المستلم',
    recipient_name: 'اسم المستلم',
    manual_orders: 'الالتباس بالطلبات اليدوية',
    get_quotes: 'طلب عرض أسعار الشحن',
    freight_orders: 'طلبات شحن البضائع',
    request_quote: 'طلب تسعير للشحنة',
    manage_stock: 'إدارة المخزون والسلع',
    your_inventory: 'مخزونك الحالي',
    invoices_payment: 'الفواتير والمدفوعات اللوجستية',
    warehouse_orders: 'طلبات المستودع والمخازن',
    ecommerce: 'منصات التجارة الإلكترونية',
    couriers: 'شركات التوصيل السريع',
    analytics: 'التحليلات ومؤشرات الأداء',
    statements: 'كشوفات الحساب والمدفوعات',
    cod_payments: 'مدفوعات الدفع عند الاستلام',
    tax_reports: 'التقارير الضريبية المعتمدة',
    freight_invoices: 'فواتير الشحن والخدمات اللوجستية',
    previous_orders: 'الطلبات السابقة والمكتملة',
    view_all_orders: 'عرض جميع الطلبات النشطة',
    recipient: 'المستلم والمعني بالطلب',
    recipient_address: 'عنوان التسليم للمستلم',
    couriers_directory: 'دليل المناديب وأسطول التوصيل',
    couriers_desc: 'تتبع ومراقبة وإدارة السائقين النشطين، أنواع المركبات، ومبالغ الدفع عند الاستلام.',
    active_fleet: 'أسطول التوصيل النشط',
    vehicle_type: 'نوع المركبة',
    cod_collected_cash: 'مبالغ الدفع عند الاستلام المحصلة',
    settle_cash: 'تسوية المبالغ النقدية',
    cash_settled_success: 'تمت تسوية مبالغ الدفع عند الاستلام بنجاح!',
    tracking_map: 'خريطة التتبع الحي للمندوب',
    all_vehicles: 'جميع المركبات',
    courier_motorcycle: 'دراجة نارية',
    van: 'شاحنة صغيرة (فان)',
    sedan: 'سيارة سيدان',
    busy: 'مشغول / في الطريق',
    add_courier: 'إضافة مندوب جديد',
    total_completed_trips: 'إجمالي الرحلات المكتملة',
    performance_rating: 'مؤشر تقييم الأداء',
    availability_status: 'الحالة والنشاط',
    financial_reconciliation: 'التسوية المالية لشركات الشحن',
    financial_reconciliation_desc: 'مقارنة عروض الأسعار التقديرية مع فواتير الحجم الفعلي من شركات الشحن لاكتشاف تسرب الهامش والعمولات.',
    tracking_awb: 'التتبع / بوليصة الشحن',
    courier: 'الناقل',
    est_weight: 'الوزن التقريبي',
    actual_weight: 'الوزن الحجمي الفعلي',
    quoted_price: 'السعر المقدر',
    billed_invoice: 'الفاتورة المصدرة',
    margin_leak: 'تسرب الهامش',
    all_carriers: 'جميع شركات النقل',
    exceptions: 'استثناءات والمشاكل',
    matched: 'متطابق',
    smart_courier_options: 'خيارات التوصيل الذكية',
    found_rates: 'الأسعار المتاحة',
    select_book: 'اختيار وحجز',
    convert_quote: 'تحويل التسعيرة إلى طلب',
    standard_a4: 'ورق قياسي A4 (PDF)',
    thermal_printer: 'طابعة حرارية (ZPL)',
    download_label: 'تحميل بوليصة الشحن',
    view_pdf: 'معاينة بوليصة الشحن',
    create_rma: 'إنشاء طلب استرجاع (RMA)',
    auto_fix: 'إصلاح تلقائي',
    webhook_updates: 'تحديثات نظام التتبع',
    smart_routing: 'التوجيه الذكي للمسار',
    sandbox_dispatch: 'إرسال تجريبي (Sandbox)',
    return_processing_alert: 'جاري إنشاء بوليصة الاسترجاع العكسي مع شركة التوصيل...\n\nتحقق من بريدك الإلكتروني للحصول على بوليصة الاسترجاع.',
    error_missing_location: 'خطأ: يرجى تحديد موقع الاستلام والوجهة بشكل صحيح لحساب التكلفة.',
    address_validation_alert: 'تم تطبيق التحقق من العنوان من خرائط جوجل. تمت إضافة الرمز البريدي القياسي.',
    financial_overview: 'نظرة عامة مالية',
    revenue_settlements: 'الإيرادات مقابل التسويات (أسبوعياً)',
    revenue: 'الإيرادات',
    settlements: 'التسويات',
    uae_ops_map: 'خريطة عمليات الإمارات',
    live_origin: 'منشأ الطلبات المباشرة في أنحاء الإمارات',
    merchant_api: 'API التجار',
    mobile_apps: 'تطبيقات الهاتف',
    b2b_integrations: 'الربط المباشر مع الشركات',
    manual_entry: 'إدخال يدوي',
    active_containers: 'الحاويات النشطة',
    heavy_pipelines: 'مسارات لوجستية ثقيلة نشطة',
    total_payload_weight: 'إجمالي وزن الحمولة',
    active_pallet_count: 'عدد المنصات النشطة',
    standard_block_size: 'حجم التعبئة القياسي',
    freight_turnovers: 'دوران الشحن',
    gross_billings: 'إجمالي الفواتير التجارية',
    heavy_freight_center: 'مركز عمليات الشحن الثقيل',
    shipment_id: 'رقم الشحنة',
    booked_by: 'تم الحجز بواسطة',
    delivery_path: 'مسار التوصيل',
    gross_quote: 'إجمالي التسعيرة',
    transit_status: 'حالة النقل',
    clearance_action: 'إجراءات التخليص',
    active_phone: 'رقم الهاتف النشط',
    success_rate: 'معدل النجاح',
    smart_solutions_title: 'حلول ذكية لـ',
    smart_solutions_shipping: 'الشحن',
    smart_solutions_subtitle: 'تقدم شركة USend أدوات شحن تبسط العمليات اللوجستية للشركات الحديثة',
    start_now_hero: 'ابدأ الآن',
    talk_to_sales: 'تحدث إلى المبيعات',
    about_usend: 'عن بوابة USend',
    about_usend_desc: 'نظام بيئي لوجستي رائد يربط الناقلين المحليين بالتجار بسلاسة من خلال توجيه ذكي موحد.',
    success_rate_title: 'نسبة النجاح في توصيل المنتجات في الوقت المحدد',
    about_us: 'من نحن'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    const translation = translations[language][key];
    if (translation) return translation;
    
    // Fallback formatting: capitalize first letter and remove underscores
    return key.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
